---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits
Our project will be done using a sequence of save and commits.

## First Verse 
<Put the first two verses of Jabberwocky by Lewis Carrol in this section>

’Twas brillig, and the slithy toves 
  Did gyre and gimble in the wabe: 
All mimsy were the borogoves, 
And the mome raths outgrabe. 


## Second Verse
<Put the first two verses of The Road Not Taken by Robert Frost here>
Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth;


## Last Verse
<Put a short poem of your choice 8-20 lines,here>
Edgar Allan Poe "Raven"
Once upon a midnight dreary, while I pondered, weak and weary, 
Over many a quaint and curious volume of forgotten lore, 
While I nodded, nearly napping, suddenly there came a tapping, 
As of some one gently rapping, rapping at my chamber door. 
"'Tis some visitor," I muttered, "tapping at my chamber door- 
                Only this, and nothing more." 


